steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: '3-tire-app-gcp/frontend'
    args:
      - build
      - '--build-arg'
      - 'REACT_APP_BACKEND_URL=https://backend-588700579228.asia-south1.run.app'
      - '-t'
      - 'asia-south1-docker.pkg.dev/project-dev-496407/fronted-app/frontend:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'asia-south1-docker.pkg.dev/project-dev-496407/fronted-app/frontend:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - frontend
      - '--image=asia-south1-docker.pkg.dev/project-dev-496407/fronted-app/frontend:$COMMIT_SHA'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'asia-south1-docker.pkg.dev/project-dev-496407/fronted-app/frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY